# Generated by Django 3.2.9 on 2021-12-06 05:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fieldsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
